export const LEVERANTOR_KATEGORIER = [
  'Arkitekt',
  'Armering',
  'Avfallshantering',
  'Betong',
  'Betonggolv',
  'Brandkonsult',
  'Brandskydd',
  'Brandskyddsmålning',
  'Byggbeslag',
  'Dörrleverantör',
  'El',
  'Entrétak',
  'Fasad',
  'Form',
  'Fuktkonsult',
  'Fönsterleverantör',
  'Geoteknik',
  'Golvajämning',
  'Golvläggning',
  'Grundmaterial',
  'HDF',
  'Hiss',
  'Håltagning',
  'Högbärande plåt',
  'Industrigolv',
  'Innerdörrar & Partier',
  'Innerväggar',
  'Kakel Klinkers',
  'Konstruktör',
  'Konsult Tillgänglighet',
  'Konsulter',
  'Kran och Lyft',
  'Kyla',
  'Larm',
  'Lift och Maskinuthyrning',
  'Ljudkonsult',
  'Lufttäthetsprovning',
  'Lås & Larm',
  'Lösull',
  'Mark',
  'Markiser',
  'Mtrl. lev',
  'Måleri',
  'Plåtslagare',
  'Portleverantör',
  'Prefabricerad Betong',
  'Projektör EL',
  'Projektör Vent',
  'Projektör VS',
  'Puts',
  'Pålningsarbete',
  'RBK mätning',
  'Rivning',
  'Sandwichpaneler',
  'Sanering',
  'Skärmtak',
  'Skåpsinredning',
  'Smide',
  'Solavskärmning',
  'Sprinkler',
  'Stomleverantör',
  'Styr',
  'Städ',
  'Ställning',
  'Ställverksgolv',
  'Ståldörrar',
  'Ståltrappor',
  'Systemväggar',
  'Takkonstruktioner',
  'Takläggare',
  'Travers',
  'Trätrappor',
  'Undergolv',
  'Undertak',
  'Ventilation',
  'Vitvaror',
  'VS',
] as const;
