import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { flex: 1, padding: 18, backgroundColor: '#fff' },
  subtitle: { fontSize: 18, fontWeight: '600', marginBottom: 8 },
  noControls: { fontSize: 16, fontStyle: 'italic', marginBottom: 12 },
  groupContainer: { marginBottom: 18, backgroundColor: '#fff', borderRadius: 12, padding: 12, borderWidth: 1, borderColor: '#e0e0e0' },
  groupHeader: { flexDirection: 'row', alignItems: 'center', flexWrap: 'nowrap', paddingVertical: 8, paddingHorizontal: 4 },
  groupTitle: { fontSize: 16, fontWeight: '700', marginLeft: 6, color: '#263238', flexShrink: 1 },
  groupBadge: { backgroundColor: '#1976D2', borderRadius: 12, paddingHorizontal: 8, marginLeft: 8 },
  groupBadgeText: { color: '#fff', fontWeight: '700', fontSize: 13 },
  controlCard: { backgroundColor: '#fff', borderRadius: 8, padding: 10, marginVertical: 4, borderWidth: 1, borderColor: '#e0e0e0', minHeight: 54, flexDirection: 'row', alignItems: 'center' },
  controlCardWeb: { width: '100%', flex: 1, alignSelf: 'stretch', paddingVertical: 4, paddingHorizontal: 10, minHeight: 40, marginVertical: 2 },
  controlTextContainer: { flexDirection: 'column', flex: 1, minWidth: 0 },
  controlTextContainerWeb: { flexDirection: 'row', alignItems: 'center', flex: 1, minWidth: 0 },
  controlLine: { flexShrink: 1 },
  controlTitle: { fontSize: 15, color: '#222', fontWeight: 'bold', flexShrink: 1 },
  controlTitleInlineWeb: { fontSize: 14, color: '#222', fontWeight: '400' },
  controlSubtitle: { color: '#555', fontSize: 13, marginTop: 4, flexShrink: 1 },
  controlSubtitleInline: { color: '#555', fontSize: 12, fontWeight: '400' },
  form: { backgroundColor: '#fff', borderRadius: 12, padding: 16, margin: 12 },
  selectedType: { fontWeight: '700', fontSize: 16, marginBottom: 8 },
  infoText: { fontSize: 14, color: '#555', marginBottom: 8 },
  linkText: { color: '#1976D2', fontSize: 14, marginBottom: 8 },
  input: { backgroundColor: '#f5f5f5', borderRadius: 8, padding: 10, fontSize: 15, marginBottom: 8, borderWidth: 1, borderColor: '#e0e0e0' },
  saveButton: { backgroundColor: '#1976D2', borderRadius: 8, padding: 12, alignItems: 'center', marginTop: 8 },
  saveButtonText: { color: '#fff', fontWeight: '700', fontSize: 16 },
  cancelButton: { backgroundColor: '#e0e0e0', borderRadius: 8, padding: 12, alignItems: 'center', marginTop: 8 },
  cancelText: { color: '#222', fontWeight: '600', fontSize: 16 },
  undoBar: { backgroundColor: '#fffbe6', borderRadius: 8, padding: 10, margin: 12, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  undoText: { color: '#222', fontSize: 15 },
  undoButtonText: { color: '#1976D2', fontWeight: '700', fontSize: 15 },
  noticeBar: { backgroundColor: '#e3f2fd', borderRadius: 8, padding: 10, margin: 12 },
  noticeText: { color: '#1976D2', fontSize: 15, textAlign: 'center' },
  summaryCard: { backgroundColor: '#fff', borderRadius: 18, padding: 24, width: 320, shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.18, shadowRadius: 8, elevation: 6 },
  modalText: { fontSize: 20, fontWeight: '600', marginBottom: 18, color: '#222', textAlign: 'center', marginTop: 6 },
  filterRow: { flexDirection: 'row', flexWrap: 'wrap', marginVertical: 8 },
  filterChip: { backgroundColor: '#e0e0e0', borderRadius: 16, paddingHorizontal: 12, paddingVertical: 6, marginRight: 8, marginBottom: 8 },
  filterChipSelected: { backgroundColor: '#1976D2' },
  filterChipText: { color: '#222', fontSize: 14 },
  filterChipTextSelected: { color: '#fff', fontWeight: '700' },
  centerOverlay: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.25)' },
});

export default styles;
